### ISSUE TITLE
is not runnning

### ISSUE THREAD

**Issue by ekardian** [genom-by/LinkBox#1]
only show me blank screen and a line, can u give me a few instruction or requeriments to install?

my server:

Server version: Apache/2.4.7 (Ubuntu)
sqlite3 3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
PHP 5.6.32-1+ubuntu14.04.1+deb.sury.org+1 (cli)
mysql  Ver 14.14 Distrib 5.6.38, for Linux (x86_64) using  EditLine wrapper

**Comment by genom-by** [comment]
What is wrote in log file? (can be found at linkbox\log\logfile.log )
before running the app u should set your own sitepath and database ppath at the settings file ( linkbox\cgi\settings.inc.php )

**Comment by genom-by** [comment]
look at README.md file - described where to find these settings
